# Generated by Django 4.2.1 on 2024-04-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_published_date_book_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='book_covers/default.jpg', upload_to='book_covers/'),
        ),
    ]
